// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.algorithm.dto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:algorithm.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 a = 1;</code>
   * @return The a.
   */
  long getA();

  /**
   * <code>int64 b = 2;</code>
   * @return The b.
   */
  long getB();
}
