// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.algorithm.dto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:algorithm.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 result = 1;</code>
   * @return The result.
   */
  long getResult();
}
